version: "3"

services:

  olm:
    build:
      context: ./olm/repo/
      dockerfile: ../Dockerfile
    image: olm
    command: "true"
  
  plugin-olm:
    build:
      context: ./plugin-olm/repo/
      dockerfile: ../Dockerfile
    image: plugin-olm
    command: "true"

  kiwiirc-client:
    build:
      context: ./kiwiirc-client/repo/
      dockerfile: ../Dockerfile
    image: kiwiirc-client
    command: "true"
  
  webircgateway:
    build:
      context: ./webircgateway/repo/
      dockerfile: ../Dockerfile
    image: webircgateway
    volumes:
      - ./webircgateway.conf:/root/config.conf
      - ./kiwiirc-client.config.json:/root/www/static/config.json
    ports:
      - "30000:80"

  oragono:
    image: oragono/oragono:latest
    expose:
      - 6667
