version: "3"

services:

  olm:
    build:
      context: ./olm/olm-git/
      dockerfile: ../Dockerfile
    command: "true"
  
  plugin-olm:
    build:
      context: ./plugin-olm/plugin-olm-git/
      dockerfile: ../Dockerfile
    command: "true"

  kiwiirc:
    build:
      context: ./kiwiirc/kiwiirc-git/
      dockerfile: ../Dockerfile
    command: "true"
  
  webircgateway:
    build:
      context: ./webircgateway/webircgateway-git/
      dockerfile: ../Dockerfile
    volumes:
      - ./webircgateway.conf:/root/config.conf
      # untrusted testing cert:
      # openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365 -nodes -subj '/CN=0.0.0.0'
      - ./server.key:/root/server.key
      - ./server.crt:/root/server.crt
      - ./kiwiirc-client.config.json:/root/www/static/config.json
    ports:
      - "30000:80"
      - "30001:443"

  ircd:
    # image: inspircd/inspircd-docker
    build:
      context: ./inspircd/
    volumes:
      - ./inspircd/conf/:/inspircd/conf/
    expose:
      - 6667
