version: "3"

services:

  olm:
    build:
      context: ./olm/olm-git/
      dockerfile: ../Dockerfile
    command: "true"
  
  plugin-olm:
    build:
      context: ./plugin-olm/plugin-olm-git/
      dockerfile: ../Dockerfile
    command: "true"

  kiwiirc-client:
    build:
      context: ./kiwiirc-client/kiwiirc-git/
      dockerfile: ../Dockerfile
    command: "true"
  
  webircgateway:
    build:
      context: ./webircgateway/webircgateway-git/
      dockerfile: ../Dockerfile
    volumes:
      - ./webircgateway.conf:/root/config.conf
      - ./kiwiirc-client.config.json:/root/www/static/config.json
    ports:
      - "30000:80"

  ircd:
    # image: inspircd/inspircd-docker
    build:
      context: ./inspircd/
    volumes:
      - ./inspircd/conf/:/inspircd/conf/
    expose:
      - 6667
